# Generated by Django 4.0.3 on 2022-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('book_type', models.CharField(choices=[('FN', 'Фантастика'), ('SF', 'Научпоп'), ('IT', 'IT')], max_length=2, primary_key=True, serialize=False)),
                ('books', models.ManyToManyField(related_name='book_types', to='book_receiver.book')),
            ],
            options={
                'ordering': ['book_type'],
            },
        ),
    ]
