# Generated by Django 4.0.3 on 2022-03-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='book_type',
            field=models.CharField(choices=[('FN', 'Фантастика'), ('SF', 'Научпоп'), ('IT', 'IT'), ('CL', 'Классика')], max_length=2, primary_key=True, serialize=False),
        ),
    ]
