# Generated by Django 4.0.3 on 2022-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_receiver', '0002_book_author_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
