# Generated by Django 4.0.3 on 2022-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_receiver', '0003_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
